version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: aws-sdk
    versions:
    - "> 2.11.473, < 2.12"
  - dependency-name: "rubocop*"
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
