language: ruby
cache: bundler

rvm:
  - 2.1.6
  - 2.2
  - ruby-head

services:
  - redis-server

sudo: true

bundler_args: --jobs=3 --retry=3 --without development

before_install:
  - sh -c "if [ '$RUBYGEMS_VERSION' != 'latest' ]; then gem update --system $RUBYGEMS_VERSION; fi"
  - gem --version
  - script/install_toxiproxy.sh

before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare

script:
  - bundle exec rake
  - bundle exec rake rubocop

env:
  - RUBYGEMS_VERSION=2.4.5
  - RUBYGEMS_VERSION=latest

matrix:
  allow_failures:
    - env: "RUBYGEMS_VERSION=latest"
    - rvm: 2.2
    - rvm: ruby-head
  fast_finish: true
