before_install:
  - rvm rubygems 1.8.25
before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:create db:migrate db:test:prepare
git:
  strategy: tarball
language: ruby
rvm:
  - 1.9.3
script: bundle exec rake default
