language: ruby

cache:
  bundler: true
  directories:
    - reports
    - vendor/cache

rvm:
  - 2.6.6
  - ruby-head

addons:
  apt:
    sources:
      - elasticsearch-5.x
    packages:
      - elasticsearch
      - openjdk-8-jre-headless
  postgresql: "9.6"
  chrome: stable

services:
  - elasticsearch
  - memcached
  - docker

bundler_args: --jobs=3 --retry=3 --without development

git:
  submodules: true

before_install:
  - git submodule update --init
  - sh -c "if [ '$RUBYGEMS_VERSION' != 'latest' ]; then gem update --system $RUBYGEMS_VERSION; fi"
  - gem --version
  - script/install_toxiproxy.sh

before_script:
  - cp config/database.yml.example config/database.yml
  - bundle exec rake db:setup

script:
  - bundle exec rails test
  - bundle exec rake rubocop
  - bundle exec brakeman
  - script/build_docker.sh

env:
  - RUBYGEMS_VERSION=2.6.10
  - RUBYGEMS_VERSION=latest

matrix:
  allow_failures:
    - env: "RUBYGEMS_VERSION=latest"
    - rvm: ruby-head
  fast_finish: true
