development:
  protocol: http
  host: localhost
  s3_bucket: s3bucket
  s3_contents_bucket: contents
  s3_compact_index_bucket: compact-index
  s3_region: us-east-1
  s3_endpoint: s3.amazonaws.com
  versions_file_location: "./config/versions.list"

test:
  protocol: http
  host: localhost
  s3_bucket: test.s3.rubygems.org
  s3_contents_bucket: contents.test.s3.rubygems.org
  s3_compact_index_bucket: compact-index.test.s3.rubygems.org
  s3_region: us-east-1
  s3_endpoint: s3.amazonaws.com
  versions_file_location: "./test/helpers/versions.list"

staging:
  protocol: https
  host: staging.rubygems.org
  s3_bucket: oregon.staging.s3.rubygems.org
  s3_region: us-west-2
  s3_endpoint: s3-us-west-2.amazonaws.com
  s3_contents_bucket: contents.oregon.staging.s3.rubygems.org
  s3_compact_index_bucket: compact-index.oregon.staging.s3.rubygems.org
  versions_file_location: "./config/versions.list"

dev:
  protocol: https
  host: dev.rubygems.org
  s3_bucket: oregon.dev.s3.rubygems.org
  s3_region: us-west-2
  s3_endpoint: s3-us-west-2.amazonaws.com
  s3_contents_bucket: contents.oregon.dev.s3.rubygems.org
  s3_compact_index_bucket: compact-index.oregon.dev.s3.rubygems.org
  versions_file_location: "./config/versions.list"

production:
  protocol: https
  host: rubygems.org
  s3_bucket: oregon.production.s3.rubygems.org
  s3_region: us-west-2
  s3_endpoint: s3-us-west-2.amazonaws.com
  s3_contents_bucket: contents.oregon.production.s3.rubygems.org
  s3_compact_index_bucket: compact-index.oregon.production.s3.rubygems.org
  versions_file_location: "./config/versions.list"
  separate_admin_host: rubygems.team

webauthn-review:
  protocol: https
  host: webauthn-review.rubygems.org
  s3_bucket: oregon.webauthn-review.s3.rubygems.org
  s3_region: us-west-2
  s3_endpoint: s3-us-west-2.amazonaws.com
  s3_contents_bucket: contents.oregon.webauthn-review.s3.rubygems.org
  versions_file_location: "./config/versions.list"
