apiVersion: v1
kind: Service
metadata:
  name: unicorn
  labels:
    name: unicorn
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: unicorn
