name: ERD
on:
  pull_request:
    paths:
      - ".github/workflows/erd.yml"
      - "db/schema.rb"
      - "doc/erd.svg"
      - "doc/erd.dot"
  push:
    branches:
      - master
    paths:
      - "db/schema.rb"
      - "doc/erd.svg"
      - "doc/erd.dot"
permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  erd:
    name: Verify ERD up-to-date
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install and start database service
        run: |
          docker-compose up -d db
      - uses: ruby/setup-ruby@bc1dd263b68cb5626dbb55d5c89777d79372c484 # v1.149.0
        with:
          bundler-cache: true
      - name: Install Graphviz
        run: sudo apt-get install graphviz
      - name: Prepare environment
        run: |
          cp config/database.yml.sample config/database.yml
          bundle exec rake db:setup
      - name: Generate ERD
        run: |
          bundle exec rake erd filetype=dot filename=doc/erd-ci orientation=vertical title="RubyGems.org domain model"
      - name: Check diff
        # `tr -d "[:blank:]"`: remove horizontal whitespace to account for machine differences (works better than diff's --ignore-all-space)
        # `sort`: sorts line since Graphviz instruction order is non-deterministic
        # diff to check the source controlled-file against CI-generated file
        # Inspired by: https://github.com/voormedia/rails-erd/issues/281#issuecomment-1048721398
        run: diff --unified <(tr -d "[:blank:]" < doc/erd-ci.dot | sort) <(tr -d "[:blank:]" < doc/erd.dot | sort)
      - name: Print error
        if: ${{ failure() }}
        run: |
          echo "::error file=doc/erd.dot::ERD is out of date."
          echo "Please install Graphviz (\`brew install graphviz\`) and run \`rake gen_erd\`"
