name: Lint
on:
  pull_request:
  push:
    branches:
      - master
permissions:
  contents: read

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1.149.0
        with:
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
  brakeman:
    name: Brakeman
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1.149.0
        with:
          bundler-cache: true
      - name: Brakeman
        run: bundle exec brakeman
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        kubernetes_version: ["1.22.0"]
        environment:
          - staging
          - production
    steps:
      - name: login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - uses: ruby/setup-ruby@5311f05890856149502132d25c4a24985a00d426 # v1.153.0
        with:
          bundler-cache: true
      - name: krane render
        run: |
          gem exec --silent krane render -f config/deploy/$ENVIRONMENT --bindings=environment=$ENVIRONMENT --current-sha=$REVISION > config/deploy/$ENVIRONMENT.rendered.yaml
        env:
          ENVIRONMENT: "${{ matrix.environment }}"
          REVISION: "${{ github.sha }}"
      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          name: "${{ matrix.environment }}.rendered.yaml"
          path: "config/deploy/${{ matrix.environment }}.rendered.yaml"
      - name: kubeconform
        uses: docker://ghcr.io/yannh/kubeconform:v0.6.3
        with:
          entrypoint: "/kubeconform"
          args: "-strict -summary -output json --kubernetes-version ${{ matrix.kubernetes_version }} config/deploy/${{ matrix.environment }}.rendered.yaml"
